- name: Upgrade ubuntu to the latest release
  hosts: all
  tags:
    - release-upgrade
  tasks: 
    - name: Perform dist upgrade | packages
      ansible.builtin.apt:
        upgrade: dist
    - name: Upgrade dist to the latest release
      command: do-release-upgrade -f DistUpgradeViewNonInteractive
      register: dist_upgrade_out
      when: >
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version <= "20.04")
      notify:
        - reboot-server
    - debug:
        msg: dist_upgrade_out.stdout_lines
      when: >
        (ansible_distribution == "Ubuntu" and
        ansible_distribution_version <= "20.04")
  handlers:
    - name: reboot-server
      ansible.builtin.reboot:


- name: Create user
  hosts: all
  become: true
  tasks:
    - name: Create user iresh
      user:
        name: iresh
        groups: 'sudo'
        append: true
        state: present
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        password: "{{ 'admin' |  password_hash('sha512')}}"
    - name: Copy root authorized_keys
      copy:
        remote_src: yes
        src: /root/.ssh/authorized_keys
        dest: /home/iresh/.ssh/authorized_keys
        owner: iresh
        group: iresh
        mode: '600'

- name: Install packages
  hosts: all
  tags:
    - packages
  pre_tasks:
    - name: Upgrade existing packages
      apt:
        name: '*'
        state: latest
  tasks:
    - name: Miscellaneous packages
      apt:
        name:
          - ruby-rubygems
          - aria2
          - rclone
          - tree
          - genisoimage
          - python3-pip
          - ansible
          - expect
    - name: Miscellaneous pip packages
      block:
        - name: Packages from public repositories
          ansible.builtin.pip:
            name:
              - yq
              - yglu
              - j2cli[yaml]
            executable: pip3
        - name: Clone github repository for dp-file-uploader
          git:
            repo: https://github.com/IBM/dp-file-uploader.git
            dest: /tmp/dp-file-uploader
            version: master
            single_branch: yes
        - name: Install dp-file-uploader
          ansible.builtin.pip:
            chdir: /tmp/dp-file-uploader
            name: '.'
            executable: pip3
          
    - name: Mkpasswd gem package
      community.general.gem:
        name: mkpasswd
        state: latest
        user_install: no
    

- name: Copy config files and do configuration
  hosts: all
  become: yes
  become_user: iresh
  tags:
    - configs
  tasks:
    - name: Copy rlcone config
      block:
        - name: Ensure .config directory exists
          file:
            path: /home/iresh/.config/rclone
            state: directory
            owner: iresh
            group: iresh
        - name: Copy rclone config file
          copy:
            src: ~/.config/rclone/rclone.conf
            dest: /home/iresh/.config/rclone/rclone.conf
            owner: iresh
            group: iresh
            mode: '660'
    - name: Copy tmux config
      copy:
        src: ~/.tmux.conf
        dest: /home/iresh/.tmux.conf
        owner: iresh
        group: iresh
        mode: '660'
    - name: Vim config
      block:
        - name: clone configs repo
          git:
            repo: https://github.com/IreshMM/iresh-s-configs.git
            dest: /home/iresh/iresh-s-configs
            version: master
            single_branch: yes
        - name: Link .vimrc to repo's vimrc
          ansible.builtin.file:
            src: /home/iresh/iresh-s-configs/vim/vimrc
            dest: /home/iresh/.vimrc
            state: link
            owner: iresh
            group: iresh
    - name: Set shell vi mode
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        line: set -o vi
    - name: Set default EDITOR
      ansible.builtin.lineinfile:
        path: ~/.profile
        line: export EDITOR=vim
    - name: Git config user
      community.general.git_config:
        scope: global
        name: "{{ item['name'] }}"
        value: "{{ item['value'] }}"
      loop:
        - name: user.email
          value: socialexpz1@gmail.com
        - name: user.name
          value: Iresh Dissanayaka

- name: Ansible KVM Role
  hosts: all
  roles:
    - role: ansible-kvm
  post_tasks:
    - name: Add user iresh to the group libvirt
      user:
        name: iresh
        groups: libvirt
        append: true

- name: Download APIC files from one-drive
  hosts: all
  become: yes
  become_user: iresh
  tags:
    - apic-files
  tasks:
    - name: Download APIC files using rclone
      command: /usr/bin/rclone -c copy -P corporate-onedrive:apic-files /home/iresh/apic-files
      tags:
        - download-apic-files
    - name: Move cloud images to the pool directory
      become_user: root
      shell: |
        mv /home/iresh/apic-files/cloud-images/* /data/cloud-images
        chown -R libvirt-qemu:kvm /data/cloud-images
    - name: Extract shared devspace.zip
      unarchive:
        src: ~/apic-files/shared-devspace.zip
        dest: '~'
        remote_src: yes
        creates: ~/shared-devspace
    - name: Install apic toolkit
      become_user: root
      unarchive:
        remote_src: yes
        src: /home/iresh/apic-files/toolkit-linux.tgz
        dest: /usr/local/bin
        owner: root
        group: root
        mode: '755'
        extra_opts:
          - --transform
          - 's/apic-slim/apic/'


- name: Install apicup
  hosts: all
  tags:
    - apicup
  tasks:
    - name: Copy apicup executable to /usr/local/bin
      copy:
        remote_src: yes
        src: /home/iresh/apic-files/apicup/linux-apicup
        dest: /usr/local/bin/apicup
        owner: root
        group: root
        mode: '755'
